const CONSTS = {
    BG_FORMULAS: [
        // Математика
        "0\\notin\\mathbb{N}",
        "x^ax^b=x^{a+b}",
        "\\frac{x^a}{x^b}=x^{a-b}",
        "(x^a)^b=x^{ab}",
        "x^{-n}=\\frac{1}{x^n}",
        "x^{-n}=\\frac{1}{x^n}",
        "\\sqrt[n]{x}=x^\\frac{1}{n}",
        "\\sqrt[n]{x}=x^{n^{-1}}",
        "\\sqrt[b]{x^a}=x^\\frac{a}{b}",
        "a^2-b^2=(a-b)(a+b)",
        "(a+b)^2=a^2+2ab+b^2",
        "(a-b)^2=a^2-2ab+b^2",
        "a^3+b^3=(a+b)(a^2-ab+b^2)",
        "a^3-b^3=(a-b)(a^2+ab+b^2)",
        "(a+b)^3=a^3+3a^2b+3ab^2+b^3",
        "(a-b)^3=a^3-3a^2b+3ab^2-b^3",
        "\\sqrt{a\\pm\\sqrt{b}}=\\sqrt{\\frac{a+\\sqrt{a^2-b}}{2}}\\pm\\sqrt{\\frac{a-\\sqrt{a^2-b}}{2}}",
        "D=b^2-4ac",
        "x_{12}=\\frac{-b\\pm \\sqrt{D}}{2a}",
        "x=\\frac{-b\\pm \\sqrt{D}}{2a}",
        "x_{12}=\\frac{-b\\pm \\sqrt{b^2-4ac}}{2a}",
        "x=\\frac{-b\\pm \\sqrt{b^2-4ac}}{2a}",
        "\\Delta n=|n_{к}-n_{н}|",
        "S_{\\square}=a^2",
        "S_{▭}=ab",
        "S_{\\circ}=\\pi r^2",
        "C=2\\pi r",
        "C=\\tau r",
        "a^2+b^2=c^2",
        "c=\\sqrt{a^2+b^2}",
        "c^2=a^2+b^2-2ab\\cos\\alpha",
        "c=\\sqrt{a^2+b^2-2ab\\cos\\alpha}",
        "\\frac{sin\\alpha}{a}=\\frac{sin\\beta}{b}=\\frac{sin\\gamma}{c}",
        "\\frac{a}{sin\\alpha}=\\frac{b}{sin\\beta}=\\frac{c}{sin\\gamma}=2R",
        "\\pi\\approx3.14159",
        "\\tau\\approx6.28318",
        "\\tau=2\\pi",
        "e\\approx2.71828",
        "e=\\sum_{n=0}^{\\infty}\\frac{1}{n!}",
        "n!=\\prod_{n=1}^{c}n",
        "\\arcsin(\\sin(\\alpha))=\\alpha",
        "\\arccos(\\cos(\\beta))=\\beta",
        "e^{\\ln x}=x",
        "n^{\\log_{n} x}=x",
        "\\log_{a}(n)=\\frac{\\log_{b}(n)}{\\log_{b}(a)}",
        "\\sqrt{-1}=i",
        "e^{i\\pi}+1=0",
        "e^{i\\pi}=-1",
        "e^{i\\phi}=\\cos\\phi+i\\sin\\phi",
        "\\sin(\\phi)=\\frac{e^{i\\phi}-e^{-i\\phi}}{2i}",
        "\\cos(\\phi)=\\frac{e^{i\\phi}+e^{-i\\phi}}{2}",
        "\\sum_{n=0}^{\\infty}\\frac{f^{(n)}(a)}{n!}(x-a)^n",
        "\\lim_{x\\to c}\\frac{f(x)}{g(x)}=\\lim_{x\\to c}\\frac{f\\prime(x)}{g\\prime(x)}",
        "\\cos\\prime(x)=-\\sin(x)",
        "\\sin\\prime(x)=\\cos(x)",
        "\\int e^x=e^x",
        "\\int_{a}^{b}f\\prime(t)dt=f(b)-f(a)",
        "\\hat{f}(\\xi)=\\int_{-\\infty}^{\\infty}f(x)e^{-2\\pi ix\\xi}dx",
        "\\infty+1=\\infty",
        "\\infty-1=\\infty",
        "\\epsilon=\\frac{1}{\\omega}",
        "\\epsilon=\\omega^{-1}",
        "\\omega=\\frac{1}{\\epsilon}",
        "\\omega=\\epsilon^{-1}",
        "\\epsilon\\times\\omega=1",

        // Физика
        "m=V\\rho",
        "V=\\frac{m}{\\rho}",
        "\\rho=\\frac{m}{V}",
        "S=vt",
        "t=\\frac{S}{v}",
        "v=\\frac{S}{t}",
        "x=x_{0}+vt",
        "y=y_{0}+vt",
        "z=z_{0}+vt",
        "a=\\frac{\\Delta v}{\\Delta t}",
        "v=v_{0}+at",
        "S=v_{0}t+\\frac{at^2}{2}",
        "x=x_{0}+v_{0}t+\\frac{at^2}{2}",
        "y=y_{0}+v_{0}t+\\frac{at^2}{2}",
        "z=z_{0}+v_{0}t+\\frac{at^2}{2}",
        "g\\approx9.8\\frac{м}{с^2}",
        "g\\approx10\\frac{м}{с^2}",
        "G\\approx6,67430\\times10^{-11}\\frac{м^3}{с^2\\timesкг}",
        "G\\approx6,67430\\times10^{-11}\\frac{Н\\timesм^3}{кг^2}",
        "\\exists\\text{ ИСО}",
        "p=mv",
        "F=ma",
        "F_{т}=mg",
        "F=G\\frac{m_{1}m_{2}}{r^2}",
        "F=\\frac{\\Delta p}{\\Delta t}",
        "F=-F",
        "F_{12}=-F_{21}",
        "F_{а}=\\rho gV",
        "P=\\frac{F}{S}",
        "P=\\rho gh",
        "A=FS",
        "N=\\frac{A}{t}",
        "E=E_{к}+E_{п}",
        "E_{к}=\\frac{mv^2}{2}",
        "E_{п}=mgh",
        "Q=E",
        "Q=cm\\Delta t",
        "Q=qm",
        "Q=\\lambda m",
        "I=\\frac{q}{t}",
        "q=It",
        "R=\\rho\\frac{l}{S}",
        "P=\\frac{E}{t}",
        "U=IR",
        "I=\\frac{U}{R}",
        "R=\\frac{U}{I}",
        "P=UI",
        "1кВт\\timesч=3,6Мдж",
        "\\nu=\\frac{1}{t}",
        "\\nu=\\frac{1}{\\tau}",
        "\\nu=t^{-1}",
        "\\nu=\\tau^{-1}",
        "c\\approx299792458\\pm1,2\\frac{м}{с}",
        "\\lambda=\\frac{c}{\\nu}",
        "\\nu=\\frac{c}{\\lambda}",
        "E=mc^2",
        "h=6,62607015\\times10^{-34}Дж\\timesс",
        "\\hbar\\approx1,054571800\\times10^{-34}Дж\\timesс",
        "\\hbar\\equiv\\frac{h}{2\\pi}",
        "\\hbar\\omega=A+E_{к}",
        "\\hbar\\omega=A+\\frac{mv^2}{2}",
        "\\hbar\\omega=A+\\frac{mv^2}{2}",
        "E_{max}=h\\nu-A",
        "i\\hbar\\frac{d}{dt}|\\Psi(t)\\rangle=\\hat{H}|\\Psi(t)\\rangle",

        // Цвета
        "rgb(255,0,0)=🟥",
        "hex(\\#ff0000)=🟥",
        "rgb(255,127,0)=🟧",
        "hex(\\#ff8800)=🟧",
        "rgb(255,255,0)=🟨",
        "hex(\\#ffff00)=🟨",
        "rgb(0,255,0)=🟩",
        "hex(\\#00ff00)=🟩",
        "rgb(0,0,255)=🟦",
        "hex(\\#0000ff)=🟦",
        "rgb(127,0,255)=🟪",
        "hex(\\#8800ff)=🟪",
        "rgb(0,0,0)=⬛",
        "hex(\\#000000)=⬛",
        "rgb(255,255,255)=⬜",
        "hex(\\#ffffff)=⬜",

        // Троллинг
        "\\alpha\\beta\\gamma\\prime",
        "\\text{БАН}",
        "\\text{¯\\_(ツ)_/¯}",
        "\\text{undefined}"
    ]
}
export default CONSTS